server:
  port: 8967

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:apitable}?characterEncoding=utf8&autoReconnect=true&useSSL=${MYSQL_SSL_ENABLED:false}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:apitable@com}
    driver-class-name: com.mysql.cj.jdbc.Driver

cola:
  database:
    type: mysql